### PR TITLE
keep file order while saving

### LINKED ISSUE #152: modified ODTs have mime type of ZIP
I'm pretty sure we did some research on that already, but I'd like to keep it visible as a ticket. It's a mystery how this is possible at all...

### PR DESCRIPTION
**Pull request by andiwand**
- fix #152 
- refactor storage
- improve debug build
- fix zip directory handling
- improve zip unit tests

### CODE REVIEW

**Comment by andiwand** [comment]
@TomTasche could you test this branch?

**Comment by TomTasche** [comment]
> @TomTasche could you test this branch?

still reports as ZIP for me when using file. did it work for you?

**Comment by andiwand** [comment]
i didn't try. i was hoping that the file order will be fixed with my changes. i will troubleshoot it.

**Comment by andiwand** [comment]
@TomTasche works for me now with `file`

**Pull request merged**
