### PR TITLE
Use C++20

### PR DESCRIPTION
**Pull request by andiwand**
Time to get some more modern language features

### CODE REVIEW

**Comment by andiwand** [comment]
@TomTasche I think this will require to bump the C++ version on platform too

**Comment by TomTasche** [comment]
Android sounds easy: https://developer.android.com/ndk/guides/cpp-support#cs

But we should try iOS first...

**Comment by TomTasche** [comment]
Shall we create a test version of core with C++20 enabled so we can easily test it on platforms?

**Comment by andiwand** [comment]
https://github.com/opendocument-app/OpenDocument.ios/pull/85 looks like it's fine

**Pull request merged**
