### PR TITLE
bump c++ version to 17

### LINKED ISSUE #126: bump c++ version to 17

### PR DESCRIPTION
**Pull request by andiwand**
fix #126

### CODE REVIEW

**Comment by andiwand** [comment]
failing for clang on [travis ci](https://travis-ci.org/github/andiwand/OpenDocument.core/jobs/668044733?utm_medium=notification&utm_source=email)

**Comment by TomTasche** [comment]
meaning I don't have to try on Android yet?

**Comment by andiwand** [comment]
it builds for me locally with clang 🤔 maybe you can try as well so we know if it is a problem of the ci

**Comment by TomTasche** [comment]
Works on both iOS and Android!

**Pull request merged**
